# References
# ADB_INSTALL_TIMEOUT https://code.google.com/p/android/issues/detail?id=69735
# COVERITY SCAN: https://scan.coverity.com/travis_ci
# list of available components https://github.com/travis-ci/travis-ci/issues/2301
# For a full list, run `android list sdk -a --extended`
# TEST THIS FILE http://yaml.travis-ci.org/

language: android
jdk:
    #- openjdk7
    - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=22.0.1
    - ARMEABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
    - TARGET="android-22" NAME="android-22"

     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
    - secure: "lt79mSF5rFQbHqjj1XySe0y5IB6m6saQDtqPLphjAAm2VBk0iqjvqr2a7ywwW+vMcdFPJbXshJXK0BvNxK27OWNRLOpl98jK4tm9sGjx0VeoLTnpQ6plHemsN7vRKfyA24Oaq4uRrRw6qwMOTc9CNOol0vSc2ITKTBTsanUp7o+BySGzx6dhAFt1nVbUqf5NYvrxZkR9E8WAt3PkZkk9f10TN7ZeWe6mAq5XOhPoHXJPsrMEtWA9pNHsQNbmVU8i6aX+xzybXgXUHz3go2tv/JBvvpCGNcVfgF7pOF6DuAPaouHTr28Tc5PPeVawVwmzg+sNHmeyxyeFStOtsrU5SO6tRNr/XAZ1qXWNgEey/HUWs9SlBQi1bqi066pizFJil/L8R0lmkLDQd4dVMK27fb0odK6Z7bzZZN32QSVnnyfc16kKAcctASlt9H20BX8mWqFGAfSnqrgsF2diPbICHgYiVl/pjaKL18rif77rlZ85KePmt08lJWJ2T1FcXnjDMEUtQw2KytypJf2t5mCbW9Ztt9tA6yQyKgFsOr4YQehQHTDTgnNulxpaIsluPzeq+RBqqxnVttsVL5FvAWBCOzWDVtEClRD+WmiCD+T68U7ESRLsWONM9iV0QZYDMI1vvoKVz2XP4rzBiKuoMxXkYzGH8Vq7nFrYU1vPW17W8bk="

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    # - extra-google-m2repository
    # - addon-google_apis-google-$ANDROID_ANDROID_API_LEVEL

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

before_install:
    - ls -a
    - pwd
    # display list of all possible components
    - android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
    # display list of installed emulators
    - android list targets | grep -e '^\(\(id:\)\|\( Tag\)\)'

before_script:
  - ./adv-test.sh

script:
    - ./gradlew clean test connectedAndroidTest -PdisablePreDex

notifications:
  email: false

sudo: false

cache:
  gradlew: true
  gradle: true
  directories:
    - $HOME/.gradle

before_cache:
    # cleanup a little for better caching reuse
    - rm $HOME/.gradle/daemon/2.4/*.*
    - rm $HOME/.gradle/caches/modules-2/modules-2.lock

after_success:
- ./gradlew jacocoTestReport coveralls -PdisablePreDex

addons:
  coverity_scan:
    project:
      name: "ancho85/geostock"
    notification_email: ancho.corp@gmail.com
    build_command_prepend: "./gradlew clean --no-daemon -PdisablePreDex"
    build_command: "./gradlew build --no-daemon -PdisablePreDex"
    branch_pattern: coverity-scan

after_failure:
    - adb logcat -t 500